namespace LightenDark.Api.Types
{
    public enum ResponseTypes
    {
        Login = 2,
        MobMove = 3,
        CharacterData = 4,
        SendMessage = 7,
        StaticObjectChange = 8,
        ItemDamaged = 9,
        CharactedHpMpChanged = 10,
        CodeBook = 12,
        InventoryChanged = 14,
        ItemAction = 16,
        MapStaticCodeBook = 17,
        SkillSetChanged = 18,
        LoadBank = 22,
        BankOperation = 24,
        CraftList = 27,
        Attack = 30,
        Movement = 32,
        MobData = 33,
        CombatAction = 35,
        LoadLoot = 37,
        LoadOperation = 39,
        OrphanItems = 40,
        PlayerGraves = 41,
        BuyList = 43,
        NpcList = 45,
        ExperienceGoldChanged = 46,
        LevelUp = 47,
        Offer = 49,
        PartyData = 51,
        TradeOperation = 53,
        PowerEnchant = 55,
        Augment = 57,
        ChatMessage = 63,
        MapData = 65,
        CharacterAction = 67,
        NpcData = 68,
        PlayerFraveChanged = 72,
        hunting = 74,
        AffectChange = 75,
        Heal = 77,
        MobDamaged = 79,
        MessageBoardContent = 82,
        NpcChat = 85,
        NpcQuest = 87,
        PlayerInfo = 90,
        GmInit = 501,
        GmAllSpawn = 505,
        GmMessage = 507,
        WorldSave = 999,
        Error = 1000,
        MessageBye = 0
    }
}
